packages:
  - packages/*
  - examples/facilitator
  - examples/**/*
  - site
ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - bigint-buffer
  - bufferutil
  - keccak
  - sharp
  - unrs-resolver
  - utf-8-validate
