export const deferredEscrowABI = [
  {
    type: "constructor",
    inputs: [{ name: "_thawingPeriod", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEPOSIT_AUTHORIZATION_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FLUSH_ALL_AUTHORIZATION_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FLUSH_AUTHORIZATION_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_THAWING_PERIOD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "THAWING_PERIOD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "VOUCHER_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelThaw",
    inputs: [
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collect",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.Voucher",
        components: [
          { name: "id", type: "bytes32", internalType: "bytes32" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "valueAggregate", type: "uint256", internalType: "uint256" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "timestamp", type: "uint64", internalType: "uint64" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "escrow", type: "address", internalType: "address" },
          { name: "chainId", type: "uint256", internalType: "uint256" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collectMany",
    inputs: [
      {
        name: "vouchers",
        type: "tuple[]",
        internalType: "struct IDeferredPaymentEscrow.SignedVoucher[]",
        components: [
          {
            name: "voucher",
            type: "tuple",
            internalType: "struct IDeferredPaymentEscrow.Voucher",
            components: [
              { name: "id", type: "bytes32", internalType: "bytes32" },
              { name: "buyer", type: "address", internalType: "address" },
              { name: "seller", type: "address", internalType: "address" },
              { name: "valueAggregate", type: "uint256", internalType: "uint256" },
              { name: "asset", type: "address", internalType: "address" },
              { name: "timestamp", type: "uint64", internalType: "uint64" },
              { name: "nonce", type: "uint256", internalType: "uint256" },
              { name: "escrow", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
              { name: "expiry", type: "uint64", internalType: "uint64" },
            ],
          },
          { name: "signature", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositMany",
    inputs: [
      { name: "asset", type: "address", internalType: "address" },
      {
        name: "deposits",
        type: "tuple[]",
        internalType: "struct IDeferredPaymentEscrow.DepositInput[]",
        components: [
          { name: "seller", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositTo",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositWithAuthorization",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.DepositAuthorization",
        components: [
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "bytes32", internalType: "bytes32" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1", internalType: "bytes1" },
      { name: "name", type: "string", internalType: "string" },
      { name: "version", type: "string", internalType: "string" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
      { name: "verifyingContract", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
      { name: "extensions", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "flushAllWithAuthorization",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.FlushAllAuthorization",
        components: [
          { name: "buyer", type: "address", internalType: "address" },
          { name: "nonce", type: "bytes32", internalType: "bytes32" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "flushWithAuthorization",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.FlushAuthorization",
        components: [
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "nonce", type: "bytes32", internalType: "bytes32" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAccount",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.EscrowAccount",
        components: [
          { name: "balance", type: "uint256", internalType: "uint256" },
          { name: "thawingAmount", type: "uint256", internalType: "uint256" },
          { name: "thawEndTime", type: "uint64", internalType: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAccountDetails",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "voucherIds", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "valueAggregates", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOutstandingAndCollectableAmount",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.Voucher",
        components: [
          { name: "id", type: "bytes32", internalType: "bytes32" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "valueAggregate", type: "uint256", internalType: "uint256" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "timestamp", type: "uint64", internalType: "uint64" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "escrow", type: "address", internalType: "address" },
          { name: "chainId", type: "uint256", internalType: "uint256" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
    ],
    outputs: [
      { name: "outstanding", type: "uint256", internalType: "uint256" },
      { name: "collectable", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVoucherCollected",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "voucherId", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDepositAuthorizationNonceUsed",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "nonce", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDepositAuthorizationValid",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.DepositAuthorization",
        components: [
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "bytes32", internalType: "bytes32" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isFlushAllAuthorizationNonceUsed",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "nonce", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isFlushAllAuthorizationValid",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.FlushAllAuthorization",
        components: [
          { name: "buyer", type: "address", internalType: "address" },
          { name: "nonce", type: "bytes32", internalType: "bytes32" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isFlushAuthorizationNonceUsed",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "nonce", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isFlushAuthorizationValid",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.FlushAuthorization",
        components: [
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "nonce", type: "bytes32", internalType: "bytes32" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isVoucherSignatureValid",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        internalType: "struct IDeferredPaymentEscrow.Voucher",
        components: [
          { name: "id", type: "bytes32", internalType: "bytes32" },
          { name: "buyer", type: "address", internalType: "address" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "valueAggregate", type: "uint256", internalType: "uint256" },
          { name: "asset", type: "address", internalType: "address" },
          { name: "timestamp", type: "uint64", internalType: "uint64" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "escrow", type: "address", internalType: "address" },
          { name: "chainId", type: "uint256", internalType: "uint256" },
          { name: "expiry", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "thaw",
    inputs: [
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "DepositAuthorized",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "nonce", type: "bytes32", indexed: false, internalType: "bytes32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newBalance", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "event", name: "EIP712DomainChanged", inputs: [], anonymous: false },
  {
    type: "event",
    name: "FlushAllAuthorized",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "nonce", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "accountsFlushed", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FlushAuthorized",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "nonce", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "thawing", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ThawCancelled",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ThawInitiated",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "newThawingAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "previousThawingAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newThawEndTime", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "previousThawEndTime", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoucherAlreadyCollected",
    inputs: [
      { name: "voucherId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: false, internalType: "address" },
      { name: "totalCollected", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoucherCollected",
    inputs: [
      { name: "voucherId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "totalCollected", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoucherNoCollectableBalance",
    inputs: [
      { name: "voucherId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: false, internalType: "address" },
      { name: "outstanding", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "alreadyCollected", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "remainingBalance", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AuthorizationExpired",
    inputs: [
      { name: "expiry", type: "uint64", internalType: "uint64" },
      { name: "currentTime", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientBalance",
    inputs: [
      { name: "available", type: "uint256", internalType: "uint256" },
      { name: "requested", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidAddress",
    inputs: [{ name: "provided", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "InvalidAmount",
    inputs: [{ name: "provided", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "InvalidAsset",
    inputs: [{ name: "provided", type: "address", internalType: "address" }],
  },
  { type: "error", name: "InvalidAuthorization", inputs: [] },
  {
    type: "error",
    name: "InvalidChainId",
    inputs: [
      { name: "provided", type: "uint256", internalType: "uint256" },
      { name: "expected", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidEscrow",
    inputs: [
      { name: "provided", type: "address", internalType: "address" },
      { name: "expected", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "InvalidShortString", inputs: [] },
  {
    type: "error",
    name: "InvalidSignature",
    inputs: [
      { name: "voucherId", type: "bytes32", internalType: "bytes32" },
      { name: "buyer", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "InvalidThawingPeriod",
    inputs: [
      { name: "provided", type: "uint256", internalType: "uint256" },
      { name: "maximum", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "NoDepositsProvided", inputs: [] },
  {
    type: "error",
    name: "NoThawingInProgress",
    inputs: [
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "asset", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "NoVouchersProvided", inputs: [] },
  {
    type: "error",
    name: "NonceAlreadyUsed",
    inputs: [{ name: "nonce", type: "bytes32", internalType: "bytes32" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "StringTooLong",
    inputs: [{ name: "str", type: "string", internalType: "string" }],
  },
  {
    type: "error",
    name: "ThawingPeriodNotCompleted",
    inputs: [
      { name: "currentTime", type: "uint256", internalType: "uint256" },
      { name: "thawEndTime", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "VoucherExpired",
    inputs: [
      { name: "voucherId", type: "bytes32", internalType: "bytes32" },
      { name: "currentTime", type: "uint256", internalType: "uint256" },
      { name: "expiry", type: "uint256", internalType: "uint256" },
    ],
  },
] as const;
